# Generated by Django 4.1.2 on 2023-11-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codeK", models.TextField()),
                ("namaK", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Kriteria",
            },
        ),
        migrations.CreateModel(
            name="SubKriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k1", models.FloatField()),
                ("k2", models.FloatField()),
                ("k3", models.FloatField()),
                ("k4", models.FloatField()),
                (
                    "codeKF",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.kriteria",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "sub-Kriteria",
            },
        ),
    ]
