# Generated by Django 4.1.2 on 2023-11-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kriteria",
            name="codeK",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="subkriteria",
            name="codeKF",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.kriteria",
                to_field="codeK",
            ),
        ),
        migrations.AddConstraint(
            model_name="kriteria",
            constraint=models.UniqueConstraint(fields=("codeK",), name="unique_codeK"),
        ),
    ]
