# Generated by Django 4.1.2 on 2023-11-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_alter_kriteria_codek_alter_subkriteria_codekf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subkriteria",
            name="k1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subkriteria",
            name="k2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subkriteria",
            name="k3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subkriteria",
            name="k4",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
