# Generated by Django 4.1.2 on 2023-11-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_alter_subkriteria_k1_alter_subkriteria_k2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alternatif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nimA", models.TextField()),
                ("namaA", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Alternatif",
            },
        ),
    ]
