# Generated by Django 4.1.2 on 2023-11-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0005_alternatif"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubAlternatif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namaSA", models.CharField(max_length=255)),
                ("k1sa", models.CharField(blank=True, max_length=100, null=True)),
                ("k2sa", models.CharField(blank=True, max_length=100, null=True)),
                ("k3sa", models.CharField(blank=True, max_length=100, null=True)),
                ("k4sa", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "codeNim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.alternatif",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "sub-Alternatif",
            },
        ),
    ]
