# Generated by Django 4.1.2 on 2023-11-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_bobotprioritas"),
    ]

    operations = [
        migrations.CreateModel(
            name="BobotKonsistensi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k1", models.FloatField(blank=True, default=0, null=True)),
                ("k2", models.FloatField(blank=True, default=0, null=True)),
                ("k3", models.FloatField(blank=True, default=0, null=True)),
                ("k4", models.FloatField(blank=True, default=0, null=True)),
                ("bobotkons", models.FloatField(blank=True, default=0, null=True)),
                (
                    "codeBKF",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.kriteria",
                        to_field="codeK",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bobot-konsistensi",
            },
        ),
    ]
