# Generated by Django 4.1.2 on 2023-11-19 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_bobotkonsistensi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bobotkonsistensi",
            name="codeBKF",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mysite.kriteria"
            ),
        ),
        migrations.CreateModel(
            name="NormalisasiTopsis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k1", models.FloatField(blank=True, default=0, null=True)),
                ("k2", models.FloatField(blank=True, default=0, null=True)),
                ("k3", models.FloatField(blank=True, default=0, null=True)),
                ("k4", models.FloatField(blank=True, default=0, null=True)),
                (
                    "namaAlter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.subalternatif",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Normalisasi-Topsis",
            },
        ),
    ]
