# Generated by Django 4.1.2 on 2023-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0009_alter_bobotkonsistensi_codebkf_normalisasitopsis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternatif",
            name="nimA",
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name="alternatif",
            constraint=models.UniqueConstraint(fields=("nimA",), name="unique_nimA"),
        ),
    ]
