# Generated by Django 4.1.2 on 2023-11-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0010_alter_alternatif_nima_alternatif_unique_nima"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalBobotTopsis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k1", models.FloatField(blank=True, default=0, null=True)),
                ("k2", models.FloatField(blank=True, default=0, null=True)),
                ("k3", models.FloatField(blank=True, default=0, null=True)),
                ("k4", models.FloatField(blank=True, default=0, null=True)),
                (
                    "nimAlter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.alternatif",
                        to_field="nimA",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Normalisasi-Bobot-Topsis",
            },
        ),
    ]
