# Generated by Django 4.1.2 on 2023-11-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_normalbobottopsis"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternatif",
            name="kelasA",
            field=models.TextField(blank=True, null=True),
        ),
    ]
