# Generated by Django 4.1.2 on 2023-11-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0013_remove_alternatif_kelasa_kriteria_kelask"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopsisSolusi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("k1", models.FloatField(blank=True, default=0, null=True)),
                ("k2", models.FloatField(blank=True, default=0, null=True)),
                ("k3", models.FloatField(blank=True, default=0, null=True)),
                ("k4", models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                "verbose_name_plural": "Topsis-Solusi",
            },
        ),
    ]
