# Generated by Django 4.1.2 on 2023-11-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0015_jarakpreftopsis"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingTopsis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "nimAlter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.alternatif",
                        to_field="nimA",
                    ),
                ),
                (
                    "preferensi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.jarakpreftopsis",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ranking-Topsis",
            },
        ),
    ]
